### ISSUE TITLE
 How to limit the upload image files

### ISSUE THREAD

**Issue by gori1990** [Xety/Cake3-Upload#12]
How to limit the upload image files and select  only image file

**Comment by Xety** [comment]
Hello,

What you means about "limit the upload image files" ?

For the restriction about image files, you need to use validation rules. You can see an exemple there : https://github.com/Xety/Xeta/blob/master/src/Model/Table/UsersTable.php#L184-L198

**Comment by gori1990** [comment]
I use this plugin to upload image on the server and you want to block transmission of other types of files

**Comment by gori1990** [comment]
OK, thank you very much
