### ISSUE TITLE
is usage instruction complete?

### ISSUE THREAD

**Issue by bobombolo** [Xety/Cake3-Upload#7]
I have followed the instructions on a fresh install and my model saves without errors (after nixing out all the validation rules for my image model), but no file is saved in the webroot/img/foldername. no information is saved to the database either, other than an empty row (except id).

apologies, I'm new to cakePHP 3.0,

**Comment by jpruizs** [comment]
Hey, how you been able to make this plugin work?
Thanks

**Comment by Xety** [comment]
Hey,
Sorry for the late reply, is these comments still relevant ?
